ex6: ex6.cpp
	g++ -g -Wall -I/usr/local/mosek/7/tools/platform/linux64x86/h -o ex6 ex6.cpp -L/usr/local/mosek/7/tools/platform/linux64x86/bin -lmosek64 -lmosekxx7_0 -lmosekjava7_0 -liomp5 -lmosekscopt7_0
